server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: test
      username: hello
      password: hello

logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
